version: '2'
services:
  ws_shop:
    build: ./ws_shop
    container_name: ws_shop
#    entrypoint: ["java", "-jar","/ws_shop-1.0.jar"]
    ports:
     - 9000:9000

  ws_warehouse:
    build: ./ws_warehouse
    container_name: ws_warehouse
#    entrypoint: ["java", "-jar","/ws_warehouse-1.0.jar"]
    ports:
     - 9001:9001
